### ISSUE TITLE
builder-base is updated

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/builder-nodejs#185]
Guys, builder base is updated and these language extensions are still not updated. I am waiting to get the new jx bug fixes on the builder nodejs...What is the release process all these language specific repos follows ??

**Comment by rawlingsj** [comment]
It looks like the CRON job to trigger the language builder images isn't working.  We aimed to set it to once per day.  Let me reinstate the build on every release for now and we'll figure out the CRON.  

Thanks for reporting, I'll manually trigger a full release now.

**Comment by ysaakpr** [comment]
Awsome...really appreciate your time...was waiting for it from last couple of days..
